### ISSUE TITLE
Passing an alias as an option to a macro results in an error

### ISSUE THREAD

**Issue by lessthanseventy** [adobe/elixir-styler#147] opened 2024-03-29 04:41 UTC
## Versions

* Elixir: use `elixir --version`
Erlang/OTP 26 [erts-14.2.3] [source] [64-bit] [smp:20:20] [ds:20:20:10] [async-threads:1] [jit:ns]
Elixir 1.14.4 (compiled with Erlang/OTP 23)

* Styler: use `mix deps | grep locked | grep styler`
locked at 0.11.9 (styler) 8b7806ba
## Example Input

```elixir
defmodule Foo.Bar.TestModule do
  alias Foo.Module

  use Foo.Operation,
    type: :db_write,
    input: [
      module: %Module{},
      name: String.t()
    ],
    ok_return: %Module{},
    error_return: %Ecto.Changeset{}
...

```

## Stacktrace / Current Behaviour
Gets re-written where the alias is below the use, and causes a compiler error

**Comment by novaugust** [comment] 2024-03-29 14:55
hey there, this is covered in the [readme here](https://github.com/adobe/elixir-styler?tab=readme-ov-file#alias-dependency)
there's also an open issue on a possible perma fix in #137, so i'll close this as a dupe of that =)

**Closed by novaugust** 2024-03-29 14:55 UTC
