### ISSUE TITLE
comments inside multi-line function head moved

### ISSUE THREAD

**Issue by mxgrn** [adobe/elixir-styler#122] opened 2024-01-19 03:14 UTC
## Versions

* Elixir:

Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
Elixir 1.16.0 (compiled with Erlang/OTP 26)

* Styler:
locked at 0.11.5 (styler) ed924524

## Example Input

```elixir
  # User starts a bot the very first time
  def parse(%{
        "message" => %{
          # "chat" => %{
          # },
          "date" => 1_703_681_728,
          "entities" => [%{"length" => 6, "offset" => 0, "type" => "bot_command"}],
          "from" =>
            %{
              # "language_code" => "en",
            } = user_data,
          "message_id" => _message_id,
          "text" => "/start"
        },
        "update_id" => 53_180_247
      }) do
  end
```

## Current Behaviour

```elixir
  # User starts a bot the very first time
  # "chat" => %{
  # },
  # "language_code" => "en",
  def parse(%{
        "message" => %{
          "date" => 1_703_681_728,
          "entities" => [%{"length" => 6, "offset" => 0, "type" => "bot_command"}],
          "from" => %{} = user_data,
          "message_id" => _message_id,
          "text" => "/start"
        },
        "update_id" => 53_180_247
      }) do
  end
```

## Expected behavior

I would like my comments to stay where I put them :) Not easily solvable, I suppose.

**Comment by novaugust** [comment] 2024-01-19 04:24
ah darn, been a long time since we had one of these. thanks for the issue, i'd prefer your comments stay where you had them also!
the problem is, styler's trying to trick the formatter into writing your function head as one-line, its preferred style. styler itself is oblivious to whether there's any hope for it or not (as there clearly isn't in this case), but a side effect of making the function head into a oneliner (which formatter splits back out) is that all your comments got moved out of the head...
so yes, in short, nothing for it. i realize this is probably a big pain when you're auto formatting on save. apologies for that

**Comment by mxgrn** [comment] 2024-01-19 04:42
Thanks for the details!

> styler's trying to trick the formatter into writing your function head as one-line

Could we trade this off? Meaning, not try to convert the function head into one line.

**Comment by novaugust** [comment] 2024-01-19 14:32
yep, [deleting this line wold do it](https://github.com/adobe/elixir-styler/blob/main/lib/styler.ex#L24)

**Comment by novaugust** [comment] 2024-01-23 22:10
closing this as there's no fix planned. thanks for the issue though

**Closed by novaugust** 2024-01-23 22:10 UTC
